### ISSUE TITLE
RTCGA.RPPA biocunductor release

### ISSUE THREAD

**Issue by wchodor** [RTCGA/RTCGA.data#10]
I have prepared the package. Is it possible for factory maintainer @MarcinKosinski to sumbit this package to bioconductor?

**Comment by MarcinKosinski** [comment]
Could you also add an example to `downloadTCGA` function? in `RTCGA` package?

**Comment by MarcinKosinski** [comment]
I've added documentation to your package since you had not set roxygen2 options in project global options. Be sure to set this for every new repo you create
![use_roxygen](https://cloud.githubusercontent.com/assets/6773454/11016361/b0f4fa0a-857f-11e5-8c9b-342dac9369ba.png)

**Comment by MarcinKosinski** [comment]
Package has been submitted to bioconductor. Revision process can be seen on this issue:
https://tracker.bioconductor.org/issue1335
@wchodor

**Comment by MarcinKosinski** [comment]
https://github.com/RTCGA/RTCGA.rppa/commit/7f23aba5de19d229f775a28b692d6e498e0a2133
