### ISSUE TITLE
New package RTCGA.miRNASeq

### ISSUE THREAD

**Issue by wchodor** [RTCGA/RTCGA.data#11]
Look at files with data
````
Merge_mirnaseq__illuminaga_mirnaseq__bcgsc_ca__Level_3__miR_gene_expression__data.Level_3
Merge_mirnaseq__illuminahiseq_mirnaseq__bcgsc_ca__Level_3__miR_gene_expression__data.Level_3
````
for genes' expressions.

ga i hiseq  are two different machines that produce data (Illumina Genome Analyzer, Illumina HiSeq 2000)

For each cohort we would like to have 1 datasaet cohort.mirna which would be a bind by rows operation with an extra columns specifying from which machine is each sample

**Comment by MarcinKosinski** [comment]
When this will be done it would be great to have new `readTCGA` method to read this dataset
and to upload
`datasetsTCGA` file with new dataset information and then to submit this new package to bioconductor

**Comment by MarcinKosinski** [comment]
gdac.broadinstitute.org

**Comment by MarcinKosinski** [comment]
remeber to install the newest package from github:
`devtools::install_github('RTCGA/RTCGA')`

**Comment by MarcinKosinski** [comment]
@wchodor  Would like to fight with this pretty inconvenient package or would like to create `mrna` package where there is only 1 possible dataset?

`Merge_transcriptome__agilentg4502a_07_3__unc_edu__Level_3__unc_lowess_normalization_gene_level__data.Level_3` ?

Then I could take this package, and you could go with easier `mrna` one?

**Comment by wchodor** [comment]
OK I will take careof  `mrna` datasets. I must believe that this is the right data set for this package.

**Comment by MarcinKosinski** [comment]
It is. Use knowledge, not faith :)

2015-11-12 9:33 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
A method for reading  `mrna` data has been added to readTCGA https://github.com/RTCGA/RTCGA/commit/0afc28464b6a3201aea92cb7d9aa7a5b6a49d16d :)

**Comment by MarcinKosinski** [comment]
Could you kindly please extend the documentation of the `readTCGA` for the `miRNASeq` datasets:
https://github.com/RTCGA/RTCGA/blob/master/R/readTCGA.R#L5-#L19 :)?

**Comment by wchodor** [comment]
You can find it here:
https://github.com/wchodor/RTCGA/commit/c514142735f5b2d08a52cc0ebfcae3a1f97468b0
