### ISSUE TITLE
New release date for GDAC.BROADCAST TCGA data

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA.data#17]
The datasets have been finally uploaded with the newest snapshot. @wchodor  could you please upload your data packages with the newest date of release? I mean `RPPA`, `miRNASeq` and `mRNA` ?

I'll upload `clinical`, `mutations`, `rnaseq`, `CNV`, `methylation`.

Remember to change date of release in

- `DESCIRPTION` file
- `NEWS.md` file
- package vignette

````{R}
> library(RTCGA)
Loading required package: knitr
Welcome to the RTCGA (version: 1.1.8).
> tail(checkTCGA('Dates'))
[1] "2015-02-02" "2015-02-04" "2015-04-02" "2015-06-01" "2015-08-21" "2015-11-01"
> 
````

**Comment by wchodor** [comment]
OK, I will do it.

**Comment by MarcinKosinski** [comment]
Great!


2015-12-02 15:17 GMT+01:00 Witold Chodor <notifications@github.com>:
