### ISSUE TITLE
Family publication and datasets' dates of release

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA.data#4]
Currently the newest date of release is `"2015-06-01"`
````{Ruby}
library(RTCGA)
availableDates() %>% tail(3)
[1] "2015-02-04" "2015-04-02" "2015-06-01"
````
Before publishing I think we should have the newest available datasets in our `RTCGA.data` family of packages. In `rnaseq`,`clinical` and `mutations` datasets are from ` "2015-04-02"`

**Comment by MarcinKosinski** [comment]
I would publicate the newest version of `rnaseq` data but when I downloded and untarred files I can not  read them into R :| 
I've posted this problem on [this stack question](http://stackoverflow.com/questions/31574761/r-doesnt-see-a-file-that-exists-on-a-disk) ...

**Comment by pbiecek** [comment]
Is it a problem with length of path name? If so name of the directory can be shorten

**Comment by MarcinKosinski** [comment]
It was a problem with to long files path.

**Comment by MarcinKosinski** [comment]
There was new publication of datasets:
````{Ruby}
> library(RTCGA)
> tail( checkTCGA('Dates') )
[1] "2014-12-06" "2015-02-02" "2015-02-04" "2015-04-02" "2015-06-01" "2015-08-21"
````

I think we should update our family in few days time.

**Comment by pbiecek** [comment]
Maybe we should create an R script (or function) for each package, that will update all datasets in the given package?
Something like 'updateDatasets.R'

**Comment by MarcinKosinski** [comment]
Maybe we could. I've got easy and short scripts which do so and they are
included in RTCGA.clinical, RTCGA.mutations, RTCGA.cnv vignettes and I just
press knit :)

2015-08-25 3:26 GMT+02:00 pbiecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Datasets from 08-21 are no available yet, but they are almost 100% finished, so we should be prepared for updating packages [http://gdac.broadinstitute.org/runs/stddata__2015_08_21/](http://gdac.broadinstitute.org/runs/stddata__2015_08_21/)

**Comment by MarcinKosinski** [comment]
About that script you mentioned.

Maybe we could prepare scripts to update packages, and when
On that websie [http://gdac.broadinstitute.org/runs/stddata__latest/](http://gdac.broadinstitute.org/runs/stddata__latest/) date changes from the one that is now, to the newest one we should then run those scripts to upload our packages. It would be great if it could be run everyday with a cron job, so that we would not have to upload datasets manually.

**Comment by sahilseth** [comment]
Guys, this pkg is quite cool! I was trying to do this for clinical data myself; until of course I discovered this package. 

For teaching etc, version of firehose is not that imp. but for publication reproducibility is critical. I see that each data.set is a data.frame, would be great to have the meta-information embedded them them regarding the version of std data used as input. So a user can get the meta-info of a dataset using, version(dataset).

How about setting up a DRAT repo install of github, its faster and lightweight. And can provide updated datasets, faster than bioconductor.

For example I tried installing clinical, but it downloaded the whole repo first (and installed a sub-folder):

```
install_github("mi2-warsaw/RTCGA.data/RTCGA.clinical")
Downloading GitHub repo mi2-warsaw/RTCGA.data@master
Installing RTCGA.clinical
```


Happy to ctb, since I use these datasets often.

**Comment by MarcinKosinski** [comment]
Hi @sahilseth  - you shouldnt't install packages from this repo (I mean clinical, mutations and rnaseq) since the development has been moved to bioconductor's SVN (I am currently working on synchronizing SVN with git repo on GitHub to automatically commit to SVN repo and this or other GitHub repo).  In future `.cvn` and  new `.rppa` (and I have plans for 5 more packages)  package will also be moved to bioconductor.

The installation of packages is explained here:
https://github.com/mi2-warsaw/RTCGA.data/blob/master/README.md

I don't think DRAT repo is neccessary since TCGA releases are less often than 3 months.

But I like the idea with `version` function. I agree that information about data in manual page of for example `?cancer.mutations` might be not enough.

I am also thinking about spiltting this repository into separate repositories for each package,since it will be easier to synchronize them with bioconductor's SVN repositories (witch currently have datasets from newer release date). I will clean this repo and plans on this weekend :)

**Comment by sahilseth** [comment]
Yes, splitting would be great. May be you could start a organization by RTCGA and add all these in them. 

Also creating github tags marked with tcga stddata release would be quite cool as well.

**Comment by MarcinKosinski** [comment]
@all I'd like to just inform that we have landed in the new organization. I encourage you all to collaborate.
CC @wchodor
