### ISSUE TITLE
RTCGA.CNV download and Bioconductor release

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA.data#6]
Could you please upload somewhere code describing how do you upload `cnv` data to `RTCGA.cnv` package?

Something like [this](https://github.com/mi2-warsaw/RTCGA.data/blob/master/RTCGA.rnaseq/vignettes/downloading_rnaseq_datasets.Rmd) would be OK. Note that now downloaded files with RTCGA::downloadTCGA` are by default untarred and the `tar.gz` file is being removed after untarring.

**Comment by pbiecek** [comment]
Here: https://github.com/mi2-warsaw/RTCGA.data/blob/master/rticle/download_cnv.Rmd
is the old instruction.

**Comment by MarcinKosinski** [comment]
RTCGA.cnv has been updated a little ( https://github.com/RTCGA/RTCGA.cnv/commit/1de367c3e8e5363e1ab5d33fa7d7100a97d056d1 ) for submission and finally submitted to Bioconductor: https://tracker.bioconductor.org/issue1335
