### ISSUE TITLE
Random suggestion, use of TCGA std data version in R package version.

### ISSUE THREAD

**Issue by sahilseth** [RTCGA/RTCGA.data#8]
We often refer to TCGA data's version with the Broad's std data date (2015_08_21). 

Would you like this date to be included as part of the R package version? (might make things simpler).

- version number: 2015.08.21.XXX
- OR 1.1.20150821

Although former is better.

**Comment by sahilseth** [comment]
This way, if one does session_info(), toga data version gets automatically included.

**Comment by MarcinKosinski** [comment]
I'll think about it, and probaly will add this during this weekend on the release of new packages in RTCGA.data family :)

**Comment by sahilseth** [comment]
Awesome, what all (types of data), are you planning to add?

**Comment by MarcinKosinski** [comment]
First there's a plan that @wchodor will add RPPA :) We are also thinking about Metylation datasets. That's what I remember on the run.

Marcin Kosinski

Dnia 3 lis 2015 o godz. 18:27 sseth <notifications@github.com> napisał(a):

**Comment by sahilseth** [comment]
Cool! I started playing with methylation, will share what I have. Having two platforms makes it a little tricky.

On November 3, 2015 at 12:01:49 PM, Marcin Kosiński (notifications@github.com) wrote:

First there's a plan that @wchodor will add RPPA :) We are also thinking about Metylation datasets. That's what I remember on the run.

Marcin Kosinski

Dnia 3 lis 2015 o godz. 18:27 sseth <notifications@github.com> napisał(a):

> Awesome, what all (types of data), are you planning to add?
>
> —
> Reply to this email directly or view it on GitHub.
>
—
Reply to this email directly or view it on GitHub.

-- 

Sent with Airmail

**Comment by wchodor** [comment]
@sahilseth . We have changed the DESCRIPTION file according to your suggestion. Here is the link to a new DESCRIPTION file:
https://github.com/RTCGA/RTCGA.rppa/blob/master/DESCRIPTION

**Comment by MarcinKosinski** [comment]
Ok it's already in use for packages submitted to bioconductor.
